[package]
name = "riskless"
version = "0.1.0"
edition = "2024"
description = "A pure Rust implementation of Diskless Topics"
license = "Apache-2.0"

[dependencies]
object_store = "0.12.0"
uuid = "1.16.0"
