name: Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [ opened, synchronize, reopened ]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
    - name: Clippy
      run: cargo clippy --all-features --all-targets 
    - name: Run tests
      run: cargo test --verbose
